# Generated by Django 5.0.3 on 2024-05-05 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listingid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('basebid', models.DecimalField(decimal_places=2, max_digits=60)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('imageurl', models.URLField(blank=True)),
                ('ursid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlisting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
