# Generated by Django 5.0.3 on 2024-05-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='ursid',
            new_name='usrid',
        ),
    ]
