# Generated by Django 5.0.3 on 2024-05-14 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bid_id_bid_bidid_alter_bid_listingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('watchlistid', models.AutoField(primary_key=True, serialize=False)),
                ('listingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingwatchlist', to='auctions.listing')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userwatchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
