# Generated by Django 5.0.3 on 2024-05-14 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_closed_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('listingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingwatchlistcmnt', to='auctions.listing')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userwatchlistcmnt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
