# Generated by Django 5.0.3 on 2024-05-15 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listingid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listingwatchlist', to='auctions.listing'),
        ),
    ]
