# Generated by Django 5.0.3 on 2024-05-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_watchlist_listingid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('userid', 'listingid')},
        ),
    ]
