# Generated by Django 5.0.3 on 2024-05-15 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_watchlist_listingid_alter_watchlist_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listingid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingwatchlist', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userwatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
