# Generated by Django 5.0.3 on 2024-05-16 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_watchlist_listingid_alter_watchlist_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbid', to=settings.AUTH_USER_MODEL),
        ),
    ]
