# Generated by Django 5.0.3 on 2024-05-16 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_bid_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userbid', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
